input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
      match => {
          "message" => "%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:level}\s+%{NUMBER:pid}\s+---\s+\[%{DATA:application}\]\s+\[%{DATA:thread}\]\s+%{DATA:logger}\s+:\s+%{GREEDYDATA:log_message}"
      }
    }

    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }

    if "REPORT_UPLOADED" not in [log_message]{
      drop { }
    }

    grok {
      match => {
        "log_message" => "REPORT_UPLOADED \| city=%{DATA:city} \| threat=%{DATA:threat} \| expert1=%{DATA:expert1} \| expert2=%{GREEDYDATA:expert2}"
      }
    }

    mutate {
      strip => ["expert2"]
    }
}

output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]
    index => "app-logs"
    user => "elastic"
    password => "password"
    ilm_enabled => false
    manage_template => false
  }

  stdout { codec => rubydebug }
}