input {
  file {
    path => "/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} User %{GREEDYDATA:action}" }
  }
  date {
    match => ["timestamp", "yyyy-MM-dd", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]
    index => "app-logs"
    user => "elastic"
    password => "password"
    ilm_enabled => false
    manage_template => false
  }

  stdout { codec => rubydebug }
}